name: Run tests
# run-name: ${{ github.actor }} activo el flujo de trabajo
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  Pipeline:
    name: Test, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: 16.18
      - name: Install Dependencies
        run:  npm install
              npm install --save-dev jest
      - name: Run tests
        run:  npx jest
  
      - name: Build 
        run:  npm install eslint --save-dev
              npm install @babel/cli @babel/preset-env --save-dev
              npm run build

      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
        run:  npx netlify-cliv deploy --dir=public --prod