name: Build
# run-name: ${{ github.actor }} activo el flujo de trabajo
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest 
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18 
      
      - name: Install dependencies
        run:  npm install
              npm ci 
              npm install eslint eslint-plugin-react --save-dev
              npm install @babel/cli @babel/core @babel/preset-env --save-dev
              npm install --save-dev jest

      - name: Run compilation
        run: npm run build
        
      #NotificacionTestSlack:
      - name: Envio de notificacion Slack - Compilacion Fallida
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          text: |
                ¡Atención! La compilacion falló. Commit no fusionado en el repositorio.
                Autor: ${{ github.actor }}
                Commit: ${{ github.sha }}
                Mensaje: ${{ github.event.head_commit.message }}
          channel: #canal-de-difusion-repositorio
      
      - name: Run tests
        id: tests
        if: ${{ !failure() }}
        run:  npx jest
  
      #NotificacionTestSlack:
      - name: Envio de notificacion Slack - Tests Fallidos
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: ${{ needs.Build.outputs.tests.result == 'failure'}}
        with:
          status: ${{ job.status }}
          text: |
                ¡Atención! Los tests fallaron. Commit no fusionado en el repositorio.
                Autor: ${{ github.actor }}
                Commit: ${{ github.sha }}
                Mensaje: ${{ github.event.head_commit.message }}
          channel: #canal-de-difusion-repositorio

  sonarcloud:
    name: SonarCloud
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploy:
    name: Deploy
    needs: [Build] 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID}}
          api-key: ${{ secrets.RENDER_API_KEY}}
      
      #NotificacionDeploySlack:
      - name: Envio de notificacion Slack - Despliegue comenzado
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: ${{ !failure() }}
        with:
          status: ${{ job.status }}
          text: |
                  Se ha realizado un push en el repositorio. Comenzó un nuevo despliegue en el entorno de review.
                  Autor: ${{ github.actor }}
                  Commit: ${{ github.sha }}
                  Mensaje: ${{ github.event.head_commit.message }}
          channel: #canal-de-difusion-repositorio

      - name: Envio de notificacion Slack - Despliegue fallido
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          text: |
                  ¡Atención! El despliegue en el entorno falló.
                  Autor: ${{ github.actor }}
                  Commit: ${{ github.sha }}
                  Mensaje: ${{ github.event.head_commit.message }}
          channel: #canal-de-difusion-repositorio