name: Run tests
# run-name: ${{ github.actor }} activo el flujo de trabajo
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  Pipeline:
    name: Test, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: 16.18 
              
      - name: Run tests
        run:  npm install jest
              npx jest
  
      - name: Build 
        run:  npm install
              npm install eslint --save-dev
              npm install @babel/cli @babel/preset-env --save-dev
              npm run build
